import "@/styles/globals.css";

import { Inter } from "next/font/google";
import { getServerSession } from "next-auth/next";

import dynamic from "next/dynamic";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Shield Stack",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const Navbar = dynamic(() => import("./components/navbar"), {
    ssr: false,
  });

  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <Navbar session={session} />
        {children}
      </body>
    </html>
  );
}
